# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: github-action-docker-promote
  description: Github Action that promotes docker image
  homepage: https://cloudposse.com/accelerate
  topics: ""

