name: 'Docker promote'
description: 'Promote docker image'
author: hello@cloudposse.com
branding:
  icon: 'tag'
  color: 'white'
inputs:
  organization:
    description: 'Organization'
    required: true
  repository:
    description: 'Repository'
    required: true
  registry:
    description: 'Docker registry'
    required: true
  from:
    required: false
    description: "Source tag"
  to:
    required: false
    description: "Target tags"
  metadata:
    required: false
    description: "Get tags from git"
    default: "true"
  login:
    description: 'Docker login'
    required: false
    default: ''
  password:
    description: 'Docker password'
    required: false
    default: ''
outputs:
  success:
    description: "Output result placeholder"
    value: "${{ steps.context.outputs.action-result }}"
runs:
  using: "composite"
  steps:
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        # list of Docker images to use as base name for tags
        images: |
          ${{ secrets.registry }}/${{ inputs.organization }}/${{ inputs.repository }}
        # generate Docker tags based on the following events/attributes
        tags: |
          type=sha
          type=schedule
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=raw,value=latest,enable={{is_default_branch}}
          type=sha,format=long
          ${{ inputs.to }}
        labels: |
          org.opencontainers.image.source=https://github.com/${{ inputs.organization }}/${{ inputs.repository }}

    - name: Login
      uses: docker/login-action@v2
      if: ${{ contains(inputs.registry, '.amazonaws.com') || ( inputs.login != '' && inputs.password != '' ) }}
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.login }}
        password: ${{ inputs.password }}

    - uses: edwardgeorge/jq-action@main
      id: tag
      with:
        compact: true
        raw-output: true
        input: ${{ steps.meta.outputs.json }}
        script: '.tags | map(select(test("sha-\\w{8,}"))) | first | match("sha-\\w{8,}") | .string'

    - name: Promote
      id: promote
      shell: bash
      run: |
        docker pull ${{ secrets.registry }}/${{ inputs.organization }}/${{ inputs.repository }}:${{ inputs.from }}
        TAGS=(${{ steps.meta.outputs.tags }})
        for value in "${TAGS[@]}"
        do
          docker tag ${{ secrets.registry }}/${{ inputs.organization }}/${{ inputs.repository }}:${{ inputs.from }} ${value}
          docker push ${value}
        done

    - id: result
      shell: bash
      run: |
        echo "success=true" >> $GITHUB_OUTPUT
